// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GoalController from "./goal_controller"
application.register("goal", GoalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HistoryBackController from "./history_back_controller"
application.register("history-back", HistoryBackController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import ProgressbarController from "./progressbar_controller"
application.register("progressbar", ProgressbarController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
