meta_name: "StayActive"
meta_title: "Stay Active Community"
meta_description: "Join the community for your sport, create projects and track your progress"
meta_image: "logo.png" # should exist in `app/assets/images/`
